### ISSUE TITLE
Sending stops

### ISSUE THREAD

**Issue by bruce-lindsay** [Cimpress-MCP/TimberWinR#37]
Running version 1.2.354.0. Occasionally there is an error in the TimberWinR log file from within the RedisSender method. When this happens, logs are no longer written to Redis until the service is restarted. When in this state, the service will not respond to a service request and the related process must be terminated in order to restart the service. Any recommendations?

2015-03-25 21:35:37.9080|ERROR|TimberWinR.Outputs.RedisOutput|ctstone.Redis.RedisException: ERR Protocol error: expected '$', got ' '
   at ctstone.Redis.RedisReader.ReadType(Stream stream)
   at ctstone.Redis.RedisReader.Read(Stream stream)
   at ctstone.Redis.RedisPipelineHandler.End(Boolean ignoreResults)
   at TimberWinR.Outputs.RedisOutput.RedisSender()

**Comment by efontana** [comment]
Hmm I will look into it

**Comment by bruce-lindsay** [comment]
Thanks! In case it helps at all here are some additional details. When the service is in this state the diagnostic page does still load, but the file sample times in the response stop updating. The counter .NET CLR LocksAndThreads[Current Queue Length] holds steady at 1.




Related log data.
```text
2015-04-01 12:21:05.2363|INFO|TimberWinR.Diagnostics.Diagnostics|Diagnostic(v4/v6) on Port 5141 Ready
2015-04-01 18:04:04.5194|ERROR|TimberWinR.Outputs.RedisOutput|ctstone.Redis.RedisException: ERR Protocol error: expected '$', got ' '
   at ctstone.Redis.RedisReader.ReadType(Stream stream)
   at ctstone.Redis.RedisReader.Read(Stream stream)
   at ctstone.Redis.RedisPipelineHandler.End(Boolean ignoreResults)
   at TimberWinR.Outputs.RedisOutput.RedisSender()
2015-04-01 18:04:39.5511|ERROR|TimberWinR.Outputs.RedisOutput|ctstone.Redis.RedisException: ERR Protocol error: expected '$', got ' '
   at ctstone.Redis.RedisReader.ReadType(Stream stream)
   at ctstone.Redis.RedisReader.Read(Stream stream)
   at ctstone.Redis.RedisPipelineHandler.End(Boolean ignoreResults)
   at TimberWinR.Outputs.RedisOutput.RedisSender()
2015-04-01 18:33:01.0112|ERROR|TimberWinR.Outputs.RedisOutput|ctstone.Redis.RedisException: ERR Protocol error: expected '$', got ' '
   at ctstone.Redis.RedisReader.ReadType(Stream stream)
   at ctstone.Redis.RedisReader.Read(Stream stream)
   at ctstone.Redis.RedisPipelineHandler.End(Boolean ignoreResults)
   at TimberWinR.Outputs.RedisOutput.RedisSender()
2015-04-01 18:37:16.0928|ERROR|TimberWinR.Outputs.RedisOutput|ctstone.Redis.RedisException: ERR Protocol error: expected '$', got ' '
   at ctstone.Redis.RedisReader.ReadType(Stream stream)
   at ctstone.Redis.RedisReader.Read(Stream stream)
   at ctstone.Redis.RedisPipelineHandler.End(Boolean ignoreResults)
   at TimberWinR.Outputs.RedisOutput.RedisSender()
2015-04-01 18:38:06.1247|ERROR|TimberWinR.Outputs.RedisOutput|ctstone.Redis.RedisException: ERR Protocol error: expected '$', got ' '
   at ctstone.Redis.RedisReader.ReadType(Stream stream)
   at ctstone.Redis.RedisReader.Read(Stream stream)
   at ctstone.Redis.RedisPipelineHandler.End(Boolean ignoreResults)
   at TimberWinR.Outputs.RedisOutput.RedisSender()
2015-04-01 23:24:18.2285|INFO|TimberWinR.Inputs.LogsListener|Log D:\\Logs\\Misc\\somefile_log.txt has rolled
```

diagnostic response

```json
{
  "timberwinr": {
    "version": "1.2.353.0",
    "messages": 3659,
    "startedon": "2015-04-01T12:21:01.5801439Z",
    "configfile": "C:\\Program Files (x86)\\TimberWinR\\default.json",
    "logdir": "c:\\logs",
    "logginglevel": "Info",
    "inputs": [
      {
        "log": {
          "messages": 3658,
          "type": "Win32-FileLog",
          "location": "D:\\Logs\\*.txt",
          "logSource": null,
          "codepage": 0,
          "splitLongLines": false,
          "recurse": -1,
          "files": [
            "D:\\Logs\\somefile_log.txt",
            "D:\\Logs\\Misc\\someotherfile_log.51.txt",
            "D:\\Logs\\Misc\\someotherfile_log.52.txt",
            "D:\\Logs\\Misc\\someotherfile_log.53.txt",
            "D:\\Logs\\Misc\\someotherfile_log.54.txt",
            "D:\\Logs\\Misc\\someotherfile_log.55.txt",
            "D:\\Logs\\Misc\\someotherfile_log.txt",
            "D:\\Logs\\Misc\\yetanotherfile_log_log.1.txt",
            "D:\\Logs\\Misc\\yetanotherfile_log_log.2.txt",
            "D:\\Logs\\Misc\\yetanotherfile_log_log.3.txt",
            "D:\\Logs\\Misc\\yetanotherfile_log_log.txt",
            "D:\\Logs\\Misc\\somefile_log.61.txt",
            "D:\\Logs\\Misc\\somefile_log.62.txt",
            "D:\\Logs\\Misc\\somefile_log.63.txt",
            "D:\\Logs\\Misc\\somefile_log.64.txt",
            "D:\\Logs\\Misc\\somefile_log.65.txt",
            "D:\\Logs\\Misc\\somefile_log.txt",
            "D:\\Logs\\Misc\\foofile_log.41.txt",
            "D:\\Logs\\Misc\\foofile_log.42.txt",
            "D:\\Logs\\Misc\\foofile_log.43.txt",
            "D:\\Logs\\Misc\\foofile_log.44.txt",
            "D:\\Logs\\Misc\\foofile_log.45.txt",
            "D:\\Logs\\Misc\\foofile_log.txt",
            "D:\\Logs\\Misc\\foobarfile_log.57.txt",
            "D:\\Logs\\Misc\\foobarfile_log.58.txt",
            "D:\\Logs\\Misc\\foobarfile_log.59.txt",
            "D:\\Logs\\Misc\\foobarfile_log.60.txt",
            "D:\\Logs\\Misc\\foobarfile_log.61.txt",
            "D:\\Logs\\Misc\\foobarfile_log.txt",
            "D:\\Logs\\Misc\\somefile_log.66.txt"
          ],
          "fileSampleTimes": [
            "2015-04-01T23:24:17.1191382Z",
            "2015-04-01T23:24:17.1503897Z",
            "2015-04-01T23:24:17.181639Z",
            "2015-04-01T23:24:17.2441396Z",
            "2015-04-01T23:24:17.3222673Z",
            "2015-04-01T23:24:17.4003933Z",
            "2015-04-01T23:24:17.4472682Z",
            "2015-04-01T23:24:17.478519Z",
            "2015-04-01T23:24:17.5566481Z",
            "2015-04-01T23:24:17.6347727Z",
            "2015-04-01T23:24:17.6972706Z",
            "2015-04-01T23:23:25.1340708Z",
            "2015-04-01T23:24:17.7597714Z",
            "2015-04-01T23:24:17.8535239Z",
            "2015-04-01T23:24:17.9160258Z",
            "2015-04-01T23:24:17.9941505Z",
            "2015-04-01T23:24:18.212903Z",
            "2015-04-01T23:24:18.2285382Z",
            "2015-04-01T23:24:18.2910291Z",
            "2015-04-01T23:24:18.3691551Z",
            "2015-04-01T23:24:18.4472824Z",
            "2015-04-01T23:24:18.525407Z",
            "2015-04-01T23:24:18.6035353Z",
            "2015-04-01T23:24:18.6035353Z",
            "2015-04-01T23:24:18.6816589Z",
            "2015-04-01T23:24:18.7597393Z",
            "2015-04-01T23:24:18.8379107Z",
            "2015-04-01T23:24:18.9160367Z",
            "2015-04-01T23:24:18.994164Z",
            "2015-04-01T23:24:18.0879014Z"
          ],
          "fileSizes": [
            8894462,
            10489234,
            10485829,
            10536277,
            10485861,
            10505549,
            3429998,
            10486795,
            10494887,
            10490050,
            7155827,
            10489231,
            10490862,
            10485781,
            10490211,
            10492022,
            366,
            10606446,
            10518628,
            10524805,
            10501768,
            10486804,
            2012650,
            10485939,
            10486026,
            10485900,
            10486114,
            10486003,
            4725650,
            10487220
          ],
          "fileIndices": [
            7168,
            2319,
            2973,
            7722,
            18396,
            13184,
            4417,
            2300,
            5359,
            1461,
            1118,
            2958,
            4647,
            6411,
            6775,
            7301,
            0,
            388,
            368,
            273,
            215,
            1697,
            347,
            32199,
            29322,
            26358,
            27480,
            25922,
            8483,
            5850
          ],
          "fileCreationDates": [
            "2015-01-29T18:55:11.0168532Z",
            "2015-02-27T03:15:21.2591734Z",
            "2015-02-27T05:01:30.0426752Z",
            "2015-02-27T10:49:16.6895878Z",
            "2015-03-04T21:52:00.5958981Z",
            "2015-03-19T21:35:26.1793217Z",
            "2015-03-30T20:06:28.1504456Z",
            "2015-02-12T21:23:39.733701Z",
            "2015-02-25T18:05:28.7753094Z",
            "2015-03-04T14:20:17.2056775Z",
            "2015-03-19T21:06:38.3373376Z",
            "2015-02-27T05:44:28.9308089Z",
            "2015-02-27T11:31:32.2401667Z",
            "2015-02-27T19:14:45.9499965Z",
            "2015-02-27T23:46:20.9696568Z",
            "2015-02-28T00:11:48.3376589Z",
            "2015-04-01T23:24:15.0722425Z",
            "2015-03-09T02:11:20.6051307Z",
            "2015-03-09T03:19:56.7907362Z",
            "2015-03-09T04:17:55.6502094Z",
            "2015-03-09T04:29:25.1339621Z",
            "2015-03-09T04:40:21.1979664Z",
            "2015-03-26T15:28:17.0353254Z",
            "2015-03-21T00:00:56.4699831Z",
            "2015-03-23T04:01:26.7434191Z",
            "2015-03-23T13:30:10.0137937Z",
            "2015-03-24T13:00:12.1004282Z",
            "2015-03-25T00:00:42.7645952Z",
            "2015-03-26T15:49:57.1786573Z",
            "2015-03-06T21:00:46.0757005Z"
          ]
        }
      }
    ],
    "filters": [
      {
        "json": {
          "condition": null,
          "source": "Text",
          "promote": "Text",
          "target": null,
          "type": null,
          "addfields": null,
          "addtags": null,
          "removefields": null,
          "removetag": null
        }
      }
    ],
    "outputs": [
      {
        "redis": {
          "host": "zz.yyy.xx.bbb",
          "errors": 5,
          "redis_depth": 0,
          "sent_messages": 3659,
          "queued_messages": 0,
          "port": 9999,
          "maxQueueSize": 50000,
          "overflowDiscardOldest": true,
          "interval": 5000,
          "threads": 1,
          "batchcount": 10,
          "index": "foobazbar",
          "hosts": [
            {
              "host": "zz.yyy.xx.bbb"
            }
          ]
        }
      }
    ]
  }
}

```

**Comment by bruce-lindsay** [comment]
Futher note, this has happened again but this time with no redis errors in the log prior to the last restart. Perhaps it's a deadlock on the file monitoring side?

**Comment by efontana** [comment]
Is the log being monitored rolling ?

**Comment by bruce-lindsay** [comment]
Yes

**Comment by efontana** [comment]
1.3.20.0 fixes this

**Comment by bruce-lindsay** [comment]
Thank you very much. I'll give that a try
